package com.example.mydevotional

object BibleBooks {
    val books = listOf(
        BibleBook("Gênesis", "Genesis", "GEN", 50),
        BibleBook("Êxodo", "Exodus", "EXO", 40),
        BibleBook("Levítico", "Leviticus", "LEV", 27),
        BibleBook("Números", "Numbers", "NUM", 36),
        BibleBook("Deuteronômio", "Deuteronomy", "DEU", 34),
        BibleBook("Josué", "Joshua", "JOS", 24),
        BibleBook("Juízes", "Judges", "JDG", 21),
        BibleBook("Rute", "Ruth", "RUT", 4),
        BibleBook("1 Samuel", "1 Samuel", "1SA", 31),
        BibleBook("2 Samuel", "2 Samuel", "2SA", 24),
        BibleBook("1 Reis", "1 Kings", "1KI", 22),
        BibleBook("2 Reis", "2 Kings", "2KI", 25),
        BibleBook("1 Crônicas", "1 Chronicles", "1CH", 29),
        BibleBook("2 Crônicas", "2 Chronicles", "2CH", 36),
        BibleBook("Esdras", "Ezra", "EZR", 10),
        BibleBook("Neemias", "Nehemiah", "NEH", 13),
        BibleBook("Ester", "Esther", "EST", 10),
        BibleBook("Jó", "Job", "JOB", 42),
        BibleBook("Salmos", "Psalms", "PSA", 150),
        BibleBook("Provérbios", "Proverbs", "PRO", 31),
        BibleBook("Eclesiastes", "Ecclesiastes", "ECC", 12),
        BibleBook("Cânticos", "Song of Solomon", "SNG", 8), // Also "Song of Songs"
        BibleBook("Isaías", "Isaiah", "ISA", 66),
        BibleBook("Jeremias", "Jeremiah", "JER", 52),
        BibleBook("Lamentações", "Lamentations", "LAM", 5),
        BibleBook("Ezequiel", "Ezekiel", "EZK", 48),
        BibleBook("Daniel", "Daniel", "DAN", 12),
        BibleBook("Oseias", "Hosea", "HOS", 14),
        BibleBook("Joel", "Joel", "JOL", 3),
        BibleBook("Amós", "Amos", "AMO", 9),
        BibleBook("Obadias", "Obadiah", "OBA", 1),
        BibleBook("Jonas", "Jonah", "JON", 4),
        BibleBook("Miqueias", "Micah", "MIC", 7),
        BibleBook("Naum", "Nahum", "NAH", 3),
        BibleBook("Habacuque", "Habakkuk", "HAB", 3),
        BibleBook("Sofonias", "Zephaniah", "ZEP", 3),
        BibleBook("Ageu", "Haggai", "HAG", 2),
        BibleBook("Zacarias", "Zechariah", "ZEC", 14),
        BibleBook("Malaquias", "Malachi", "MAL", 4),
        BibleBook("Mateus", "Matthew", "MAT", 28),
        BibleBook("Marcos", "Mark", "MRK", 16),
        BibleBook("Lucas", "Luke", "LUK", 24),
        BibleBook("João", "John", "JHN", 21),
        BibleBook("Atos", "Acts", "ACT", 28),
        BibleBook("Romanos", "Romans", "ROM", 16),
        BibleBook("1 Coríntios", "1 Corinthians", "1CO", 16),
        BibleBook("2 Coríntios", "2 Corinthians", "2CO", 13),
        BibleBook("Gálatas", "Galatians", "GAL", 6),
        BibleBook("Efésios", "Ephesians", "EPH", 6),
        BibleBook("Filipenses", "Philippians", "PHP", 4),
        BibleBook("Colossenses", "Colossians", "COL", 4),
        BibleBook("1 Tessalonicenses", "1 Thessalonians", "1TH", 5),
        BibleBook("2 Tessalonicenses", "2 Thessalonians", "2TH", 3),
        BibleBook("1 Timóteo", "1 Timothy", "1TI", 6),
        BibleBook("2 Timóteo", "2 Timothy", "2TI", 4),
        BibleBook("Tito", "Titus", "TIT", 3),
        BibleBook("Filemom", "Philemon", "PHM", 1),
        BibleBook("Hebreus", "Hebrews", "HEB", 13),
        BibleBook("Tiago", "James", "JAS", 5),
        BibleBook("1 Pedro", "1 Peter", "1PE", 5),
        BibleBook("2 Pedro", "2 Peter", "2PE", 3),
        BibleBook("1 João", "1 John", "1JN", 5),
        BibleBook("2 João", "2 John", "2JN", 1),
        BibleBook("3 João", "3 John", "3JN", 1),
        BibleBook("Judas", "Jude", "JUD", 1),
        BibleBook("Apocalipse", "Revelation", "REV", 22)
    )
}